@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card bg-white ">
        <h3 class="card-header bg-primary text-center text-white"><strong>স্বাগতম, এখানে আপনি আমাদের এই সেবা সম্পর্কে জানতে পারবেন</strong></h3>
        <div class="container"><hr></div>
        <div class="card-body">
            <p>কেমন আছেন সবাই, আশা কওরই ভাল আছেন, এই অ্যাপ্লিকেশান এর সাহায্যে আপনারা আমাদের মন্ত্রণালয় এ কমপ্লেইন করতে পারবেন</p>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati sequi non earum nam nostrum, quidem dolore? Facere, voluptatem. Quisquam mollitia quibusdam, laboriosam saepe expedita vel sapiente, cumque unde nemo ipsum nihil adipisci, placeat eos amet repellat explicabo quas eveniet eaque recusandae. Architecto nemo tenetur ratione dolorum accusamus rerum, iusto nulla similique, ut, error praesentium assumenda libero vero cumque explicabo! Quaerat doloribus recusandae explicabo animi vitae autem amet officiis nihil, asperiores optio vel veniam assumenda, a eius quod aperiam consequatur tempora voluptatum ad nesciunt cupiditate delectus placeat repudiandae velit. Iusto a molestias inventore unde impedit sapiente, sit eos. Blanditiis voluptatibus iusto, quidem doloremque eveniet rem veritatis ullam aperiam debitis natus quas, minus minima magnam corporis iste officiis eum repudiandae corrupti! Quo molestiae corporis, labore exercitationem recusandae nam quia a fugiat? Necessitatibus, dolorum, dolore facilis provident velit eos eveniet alias iure at temporibus expedita laboriosam nostrum, eius sed aperiam laudantium ipsam fuga quam repudiandae officiis? Excepturi quod atque quam rerum minima optio consequuntur, aliquid sequi harum! Consequatur accusantium similique facilis sequi voluptate pariatur dolores nemo inventore! Aliquam architecto ipsam dolore corporis laborum maxime? Aliquam blanditiis illum minus quod, corrupti similique illo nesciunt vitae laborum officiis debitis vel voluptatibus eaque odit laboriosam rem! Delectus odio dolore non quaerat minus fugiat nisi repudiandae, excepturi, perferendis quia voluptas suscipit id similique tempore tenetur quos nemo totam eos, sapiente possimus! Adipisci vel ex officiis aperiam assumenda atque iusto amet dolorem commodi? Maiores non vitae libero consectetur illo suscipit, laborum nemo? Dolor hic qui itaque voluptatem dignissimos nisi, repellat reprehenderit doloribus, laudantium ex officia eaque similique expedita ratione id ut et rerum veritatis recusandae illo cumque labore repudiandae quo officiis! Magnam totam esse non laudantium voluptatibus quasi cupiditate perferendis voluptatem voluptatum soluta ipsam recusandae consequatur beatae enim illo maiores quaerat atque, excepturi, quia sed sapiente veritatis explicabo ad! Labore quas accusantium mollitia eveniet iusto quasi assumenda sequi quae. Harum culpa dolor necessitatibus dicta voluptatibus in officiis autem ad, nemo porro consequatur nihil nesciunt nobis! Nemo odio accusamus debitis facilis alias recusandae molestias placeat fugiat iusto quo, aliquid eligendi enim adipisci, delectus necessitatibus? Consequatur, dolores minima distinctio explicabo itaque rerum odit similique assumenda aliquid. Quam voluptate eius asperiores, voluptatem eaque nesciunt quis earum in nam quod, perferendis voluptas architecto? Ut voluptatum incidunt vero adipisci quidem.</p>
        </div>
    </div>
</div>
@endsection
